#!/usr/bin/python3
from datetime import datetime
from io import BytesIO, StringIO
import logging
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation
import numpy as np
import streamlit as st
import pandas as pd
import plotly.express as px

from models.cache import (getClassrooms, getCurrentClassrooms, getclassSubjects)
from models.portal.admission import Admission
from models.portal.Class import Class
from models.portal.cache import current_session, current_term, term_list
from models.portal.department import Department

from models.portal.student import Student
from models.portal.subject import Subject

from models.portal.user import User
from pages import session_auth

current_user = session_auth.current_user()
if not current_user:
    st.switch_page("CHS_IGBOPE_PORTAL.py")
if current_user.isAdmin() is False:
    st.switch_page("CHS_IGBOPE_PORTAL.py")

# logging.basicConfig(level=logging.INFO)

logger = logging.getLogger(__name__)


st.set_page_config(
    page_title="Download Excel Recording Template",
    layout="wide",
    initial_sidebar_state="collapsed",
    menu_items={
        'Get Help': 'https://www.extremelycoolapp.com/help',
        'Report a bug': "https://www.extremelycoolapp.com/bug",
        'About': "# This is a header. This is an app to manage student result"
    }
)
st.title("Recording Template")



def template_sheet():
        code = st.selectbox("Class", getCurrentClassrooms())
        term_lists = term_list()
        term = st.selectbox("Term", term_lists, index=term_lists.index(current_term()))
        wb = Workbook()
        wb.properties.creator = "Solayof Pragmatics ICT Hub"
        wb.properties.description = (
            "This Excel workbook was automatically generated by the CHS Igbope "
            "Student Result Recording System built with Streamlit and Python. "
            "It provides a structured template for recording Continuous Assessment "
            "and Examination scores for students in the selected class. "
            "The file includes validated fields to prevent duplicate admission numbers "
            "and is designed to allow teachers to manually add new student records. "
            "Data handling is powered by SQLAlchemy with SQLite, while Openpyxl and "
            "Pandas are used for Excel file creation and processing. "
            "For support or inquiries, contact: solomonayofemi@gmail.com."
        )
        wb.properties.lastModifiedBy='Solomon Ayofemi Moses'
        wb.properties.title = f"{code} Students scores"
        clss = None
        if code:
            subjectlist = getclassSubjects(code)
            subjectname = st.selectbox("Subject", subjectlist)
            clss = Class.query.filter_by(code=code).one_or_none()
        if st.button("Generate Template") and clss:
            ws = wb.active
            ws.title = code
            ws.append(["ID", "FULL_NAME", "CA", "EXAM_SCORE"])
            for student in clss.students:
                 ws.append([student.id, student.fullName])

            # Adjust FULL_NAME column width
            full_name_col = 2  # FULL_NAME is column B
            max_length = len("FULL_NAME")

            for row in ws.iter_rows(min_row=2, min_col=full_name_col, max_col=full_name_col):
                for cell in row:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))

            ws.column_dimensions[get_column_letter(full_name_col)].width = max_length + 5

            # Enforce UNIQUE IDs in column A
            id_validation = DataValidation(
                type="custom",
                formula1="=COUNTIF($A:$A,A1)=1",
                allow_blank=True,
                showErrorMessage=True,
                error="Admission number must be UNIQUE",
                errorTitle="Duplicate ID"
            )

            ws.add_data_validation(id_validation)
            id_validation.add(f"A2:A1048576")  # Apply to entire column

            # Freeze header row
            ws.freeze_panes = "A2"
            wb.save(f"template-{code}.xlsx")
            logger.info(f"Generated template-{code}.xlsx successfully by {current_user.fullName}")
            st.success(f"sheet with file name: template-{code}.xlsx generated successfully")
        try:
            with open(f"template-{clss.code}.xlsx", "rb") as file:
                st.download_button(
                    label=f"Download template-{clss.code}.xlsx file",
                    data=file,
                    file_name=f"template-{clss.code}.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"
                )
                
        except FileNotFoundError:
            st.error("Generate sheet for the class first")
        if st.button(f"Generate Template for {subjectname}") and subjectname and clss:
            ws = wb.active
            ws.title = code
            ws.append(["ID", "FULL_NAME", "CA", "EXAM_SCORE"])
            students = Student.students_without_subject(
                subject_name=subjectname,
                session=current_session(),
                classroom_id=clss.id,
                term=term
            )
            print(students is None)

            if not students:
                st.warning(f"No student without record {term} {current_session()} academic session in {subjectname}")
                return

            for student in students:
                 ws.append([student.id, student.fullName])
            
            # Adjust FULL_NAME column width
            full_name_col = 2  # FULL_NAME is column B
            max_length = len("FULL_NAME")

            for row in ws.iter_rows(min_row=2, min_col=full_name_col, max_col=full_name_col):
                for cell in row:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))

            ws.column_dimensions[get_column_letter(full_name_col)].width = max_length + 5

            # Enforce UNIQUE IDs in column A
            id_validation = DataValidation(
                type="custom",
                formula1="=COUNTIF($A:$A,A1)=1",
                allow_blank=True,
                showErrorMessage=True,
                error="Admission number must be UNIQUE",
                errorTitle="Duplicate ID"
            )

            ws.add_data_validation(id_validation)
            id_validation.add(f"A2:A1048576")  # Apply to entire column

            # Freeze header row
            ws.freeze_panes = "A2"
            wb.save(f"{subjectname}-{term}-template-{clss.code}.xlsx")
            logger.info(f"Generated {subjectname}-{term}-template-{clss.code}.xlsx successfully by {current_user.fullName}")
            st.success(f"sheet with file name: {subjectname}-{term}-template-{clss.code}.xlsx generated successfully")
        try:
            with open(f"{subjectname}-{term}-template-{clss.code}.xlsx", "rb") as file:
                st.download_button(
                    label=f"Download {subjectname}-{term}-template-{clss.code}.xlsx file",
                    data=file,
                    file_name=f"{subjectname}-{term}-template-{clss.code}.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"
                )
                
        except FileNotFoundError:
            st.error(f"Generate sheet for {subjectname}-{term} first")
try:
    template_sheet()
except Exception as e:
    logger.error(f"Error in generating template sheet: {e}")
    st.error("An error occurred while generating the template sheet.")